// <auto-generated />
using System;
using CustomerWebApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerWebApi.Migrations
{
    [DbContext(typeof(CustomerDBContext))]
    [Migration("20240601055854_DBinit")]
    partial class DBinit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerWebApi.Models.Customer", b =>
                {
                    b.Property<int>("c_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("c_id"));

                    b.Property<string>("c_city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("c_dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("c_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_phone_num")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c_state")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("c_id");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
